import Tab1 from "../assets/Tab1.png";
import Tab2 from "../assets/Tab2.png";
import Tab3 from "../assets/Tab3.png";
import Tab4 from "../assets/Tab4.png";
import Tab5 from "../assets/Tab5.png";
import Tab6 from "../assets/Tab6.png";
import Company from "../assets/Company.png";
import Profile from "../assets/Profile.png";
import greenArrow from "../assets/greenArrow.png";
import redArrow from "../assets/redArrow.png";

const TableData = [
  {
    img: Tab1,
    name: "NextGen Software Ltd.",
    revenue: "€68.3M",
    netProfit: "€8.1M",
    Ebit: "26.5%",
    Cash: "€6.8M",
    WC: 52,
    icon: greenArrow,
  },
  {
    img: Tab2,
    name: " Global Tech Solutions",
    revenue: "€62.6M",
    netProfit: "€6.3M",
    Ebit: "19.3%",
    Cash: "€4.5M",
    WC: 76,
    icon: greenArrow,
  },
  {
    img: Tab3,
    name: "Innovative Tech Solutions",
    revenue: "€54.6M",
    netProfit: "€5.3M",
    Ebit: "18.5%",
    Cash: "€3.8M",
    WC: 45,
    icon: greenArrow,
  },
  {
    img: Tab4,
    name: "Creative Design Group",
    revenue: "€36.5M",
    netProfit: "€4.1M",
    Ebit: "0.9%",
    Cash: "€2.3M",
    WC: 88,
    icon: greenArrow,
  },
  {
    img: Tab5,
    name: "Digital Dynamics Inc.",
    revenue: "€30.2M",
    netProfit: "€3.9M",
    Ebit: "3.9%",
    Cash: "€1.9M",
    WC: 25,
    icon: redArrow,
  },
  {
    img: Tab6,
    name: "Helix Digital Innovations",
    revenue: "€22.3M",
    netProfit: "€0.3M",
    Ebit: "1.5%",
    Cash: "€0.8M",
    WC: 36,
    icon: redArrow,
  },
];

const CompanyData = [
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Global Tech Solutions",
    name: "Nichol James",
    Revenue: "€245M",
    Profit: "€35M",
    Ebit: "C25M",
    GrossMargin: "28.5%",
    KeyInsight: ["Strong Growth", "Growth Leader Tech"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Tech Innovation Corp",
    name: "Alex Morgan",
    Revenue: "€342M",
    Profit: "€4M",
    Ebit: "C4OM",
    GrossMargin: "CSM",
    KeyInsight: ["Good Growth", "10gh Prontability"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "NexGen Innovations",
    name: "Jordan Lee",
    Revenue: "€224M",
    Profit: "€35M",
    Ebit: "C12M",
    GrossMargin: "18.5%",
    KeyInsight: ["Robust Expansion", "Toch sector leader"],
    isProfit: false,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Supergy Solutions",
    name: "Martin Luthar",
    Revenue: "€20M",
    Profit: "€3M",
    Ebit: "C3M",
    GrossMargin: "13.6%",
    KeyInsight: ["Poor Expansion", "Lors maling"],
    isProfit: false,
    icon: redArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Vertex Global Services",
    name: "Jatin Mehta",
    Revenue: "€120M",
    Profit: "€12M",
    Ebit: "C10M",
    GrossMargin: "5.4%",
    KeyInsight: ["Restructuring Phase", "Strategie Phot"],
    isProfit: false,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Nordic Systems AB",
    name: "Jay Dublin",
    Revenue: "€310M",
    Profit: "+C15M",
    Ebit: "+C15M",
    GrossMargin: "0.6%",
    KeyInsight: ["Struggling sector: Marketing", "Loss-Making Company"],
    isProfit: false,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Pinnacle Systems",
    name: "Jay Dublin",
    Revenue: "€275M",
    Profit: "+C25M",
    Ebit: "+C25M",
    GrossMargin: "6M",
    KeyInsight: ["Reliable Retums", "Strong Balance Sheet"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Pacife Solutions",
    name: "Jay Dublin",
    Revenue: "€400M",
    Profit: "+CSM",
    Ebit: "+COM",
    GrossMargin: "16.2%",
    KeyInsight: ["Solid Financial Track Rocord", "Investor Peny"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Innovatech Dynamics",
    name: "Jay Dublin",
    Revenue: "€20M",
    Profit: "+C20M",
    Ebit: "+C20M",
    GrossMargin: "9.7%",
    KeyInsight: ["Liquidity Crunch", "High Overheads"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Techinosphere Groups",
    name: "Jay Dublin",
    Revenue: "€230M",
    Profit: "+C20M",
    Ebit: "+C20M",
    GrossMargin: "3.5%",
    KeyInsight: ["Reliable Returns", "Strength: Services"],
    isProfit: false,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Digital Innovations",
    name: "Jay Dublin",
    Revenue: "€30M",
    Profit: "+C30M",
    Ebit: "+C30M",
    GrossMargin: "7.5%",
    KeyInsight: ["Liquidity Crunch", "High Overheads"],
    isProfit: true,
    icon: redArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Pinnacle Systems",
    name: "Jay Dublin",
    Revenue: "€275M",
    Profit: "+C25M",
    Ebit: "+C25M",
    GrossMargin: "6M",
    KeyInsight: ["Reliable Retums", "Strong Balance Sheet"],
    isProfit: false,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Pacife Solutions",
    name: "Jay Dublin",
    Revenue: "€400M",
    Profit: "+CSM",
    Ebit: "+COM",
    GrossMargin: "16.2%",
    KeyInsight: ["Solid Financial Track Rocord", "Investor Peny"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Innovatech Dynamics",
    name: "Jay Dublin",
    Revenue: "€20M",
    Profit: "+C20M",
    Ebit: "+C20M",
    GrossMargin: "9.7%",
    KeyInsight: ["Liquidity Crunch", "High Overheads"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Techinosphere Groups",
    name: "Jay Dublin",
    Revenue: "€230M",
    Profit: "+C20M",
    Ebit: "+C20M",
    GrossMargin: "3.5%",
    KeyInsight: ["Reliable Returns", "Strength: Services"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Digital Innovations",
    name: "Jay Dublin",
    Revenue: "€30M",
    Profit: "+C30M",
    Ebit: "+C30M",
    GrossMargin: "7.5%",
    KeyInsight: ["Liquidity Crunch", "High Overheads"],
    isProfit: false,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Global Tech Solutions",
    name: "Nichol James",
    Revenue: "€245M",
    Profit: "€35M",
    Ebit: "C25M",
    GrossMargin: "28.5%",
    KeyInsight: ["Strong Growth", "Growth Leader Tech"],
    isProfit: true,
    icon: redArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Tech Innovation Corp",
    name: "Alex Morgan",
    Revenue: "€342M",
    Profit: "€4M",
    Ebit: "C4OM",
    GrossMargin: "CSM",
    KeyInsight: ["Good Growth", "10gh Prontability"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "NexGen Innovations",
    name: "Jordan Lee",
    Revenue: "€224M",
    Profit: "€35M",
    Ebit: "C12M",
    GrossMargin: "18.5%",
    KeyInsight: ["Robust Expansion", "Toch sector leader"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Supergy Solutions",
    name: "Martin Luthar",
    Revenue: "€20M",
    Profit: "€3M",
    Ebit: "C3M",
    GrossMargin: "13.6%",
    KeyInsight: ["Poor Expansion", "Lors maling"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Vertex Global Services",
    name: "Jatin Mehta",
    Revenue: "€120M",
    Profit: "€12M",
    Ebit: "C10M",
    GrossMargin: "5.4%",
    KeyInsight: ["Restructuring Phase", "Strategie Phot"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Pinnacle Systems",
    name: "Jay Dublin",
    Revenue: "€275M",
    Profit: "+C25M",
    Ebit: "+C25M",
    GrossMargin: "6M",
    KeyInsight: ["Reliable Retums", "Strong Balance Sheet"],
    isProfit: true,
    icon: redArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Pacife Solutions",
    name: "Jay Dublin",
    Revenue: "€400M",
    Profit: "+CSM",
    Ebit: "+COM",
    GrossMargin: "16.2%",
    KeyInsight: ["Solid Financial Track Rocord", "Investor Peny"],
    isProfit: false,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Innovatech Dynamics",
    name: "Jay Dublin",
    Revenue: "€20M",
    Profit: "+C20M",
    Ebit: "+C20M",
    GrossMargin: "9.7%",
    KeyInsight: ["Liquidity Crunch", "High Overheads"],
    isProfit: true,
    icon: greenArrow,
  },
  {
    img: Company,
    Profile: Profile,
    CompanyName: "Techinosphere Groups",
    name: "Jay Dublin",
    Revenue: "€230M",
    Profit: "+C20M",
    Ebit: "+C20M",
    GrossMargin: "3.5%",
    KeyInsight: ["Reliable Returns", "Strength: Services"],
    isProfit: false,
    icon: redArrow,
  },
];
export default TableData;
export { CompanyData };
